# spring:
#   datasource:
    # url: jdbc:sqlserver://localhost;databaseName=getsmart;encrypt=true;trustServerCertificate=true
    # username: getsmart
    # password: Thisisdb
    # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #  url: jdbc:mysql://172.17.0.30:3306/MovieFinder?useUnicode=true&characterEncoding=utf8&useSSL=true&allowPublicKeyRetrieval=true
  #  username: oric
  #  password: Panda5252!
  #  driver-class-name: com.mysql.cj.jdbc.Driver

    # url: jdbc:mariadb://172.17.0.40:3306/huvit
    # username: huvit
    # password: Huvit2@2!
    # driver-class-name: org.mariadb.jdbc.Driver

    # driver-class-name: org.h2.Driver
    # #url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
    # url: 'jdbc:h2:C:\iWaterAI\db\iwatermain'    # H2 DB 연결 주소 (Embedded Mode)
    # username: iwaterAI        # H2 DB 접속 ID (사용자 지정)
    # password: iwaterdbPass!        # H2 DB 접속 PW (사용자 지정)

  # H2 Console 설정
  # h2:
  #   console: # H2 DB를 웹에서 관리할 수 있는 기능
  #     enabled: true           # H2 Console 사용 여부
  #     path: /h2-console       # H2 Console 접속 주소
  #     settings:
  #       web-allow-others: true # 다른 사용자 접속 허용

  # # JPA 설정
  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   hibernate:
  #     ddl-auto: update        # DB 초기화 전략 (none, create, create-drop, update, validate)
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.H2Dialect
  #       format_sql: false      # 쿼리 로그 포맷 (정렬)
  #       show_sql: false        # 쿼리 로그 출력
